# Generated by Django 4.0.5 on 2022-06-13 06:50

import django.contrib.auth.validators
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='hello WOrld', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='Hello world', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='Hello world', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='documents/', verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='binod', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
