# Generated by Django 4.0.4 on 2022-05-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'College Information',
                'verbose_name_plural': 'College Information',
            },
        ),
    ]
