# Generated by Django 4.0.4 on 2022-05-16 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=300)),
                ('objective', models.CharField(max_length=300)),
                ('feature', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Administrative Body',
                'verbose_name_plural': 'Administrative Body',
            },
        ),
        migrations.CreateModel(
            name='AdvisoryBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Advisory Board',
                'verbose_name_plural': 'Advisory Board',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'History',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Message',
            },
        ),
        migrations.CreateModel(
            name='ServicesAndFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Services and Facilities',
                'verbose_name_plural': 'Services and Facilities',
            },
        ),
        migrations.CreateModel(
            name='BoardOfDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('professional_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.history')),
            ],
            options={
                'verbose_name': 'Board of Director',
                'verbose_name_plural': 'Board of Director',
            },
        ),
    ]
